source "http://rubygems.org"


# For Testing
gem "rack-test"
gem "test-unit"
gem "rspec", :require => "spec"

# For the HTTP REST API
gem "ardtweeno", "0.6.0", :path => "./"
gem "rake"
gem "sinatra"
gem "puma"
gem "typhoeus", ">= 0.6.3"
gem "serialport", ">= 1.1.0"
gem "mongo"
gem "bson_ext"
